from __future__ import annotations

from domain.business_model import BusinessModel, GeneratorProfile
from domain.models import TableInventory


def get_builtin_models() -> dict[str, BusinessModel]:
    return {
        "fast_food": BusinessModel(
            name="fast_food",
            queue_type="single_queue",
            strategy_name="fifo_fit",
            tables=[TableInventory(seats=2, count=8), TableInventory(seats=4, count=4)],
            generator_profile=GeneratorProfile(
                min_group_size=1,
                max_group_size=4,
                group_size_weights={1: 0.35, 2: 0.35, 3: 0.1, 4: 0.2},
                min_dining_duration=8,
                max_dining_duration=30,
                dining_duration_mean=18,
                dining_duration_sd=5,
            ),
            servers=3,
            ordering_type="counter_only",
            counter_order_time_min=1,
            counter_order_time_max=4,
            counter_order_time_mean=2,
            counter_order_time_sd=0.8,
            kiosks=0,
            reservation_policy="none",
            arrival_pattern="uniform",
            patience_threshold_mean=15.0,
            patience_threshold_sd=5.0,
            notes="Quick turnover. Counter ordering is fast. No reservations.",
        ),
        "fine_dining": BusinessModel(
            name="fine_dining",
            queue_type="queue_by_group_size",
            strategy_name="best_fit",
            tables=[TableInventory(seats=2, count=5), TableInventory(seats=4, count=5), TableInventory(seats=6, count=3)],
            generator_profile=GeneratorProfile(
                min_group_size=2,
                max_group_size=6,
                group_size_weights={2: 0.35, 3: 0.18, 4: 0.25, 5: 0.14, 6: 0.08},
                min_dining_duration=75,
                max_dining_duration=150,
                dining_duration_mean=105,
                dining_duration_sd=18,
            ),
            servers=4,
            ordering_type="counter_only",
            counter_order_time_min=3,
            counter_order_time_max=10,
            counter_order_time_mean=6,
            counter_order_time_sd=2,
            kiosks=0,
            reservation_policy="hybrid_allocation",
            reserved_table_percent=0.5,
            reservation_hold_before_min=15,
            reservation_hold_after_min=15,
            arrival_pattern="right_skewed",
            patience_threshold_mean=42.0,
            patience_threshold_sd=15.0,
            notes="Slow turnover. Tableside ordering by staff. Half tables reserved.",
        ),
        "casual_dining": BusinessModel(
            name="casual_dining",
            queue_type="single_queue",
            strategy_name="fifo_fit",
            tables=[TableInventory(seats=2, count=5), TableInventory(seats=4, count=6), TableInventory(seats=6, count=2)],
            generator_profile=GeneratorProfile(
                min_group_size=1,
                max_group_size=6,
                group_size_weights={1: 0.12, 2: 0.28, 3: 0.18, 4: 0.26, 5: 0.1, 6: 0.06},
                min_dining_duration=40,
                max_dining_duration=90,
                dining_duration_mean=60,
                dining_duration_sd=12,
            ),
            servers=3,
            ordering_type="counter_only",
            counter_order_time_min=2,
            counter_order_time_max=6,
            counter_order_time_mean=3,
            counter_order_time_sd=1,
            kiosks=0,
            reservation_policy="none",
            arrival_pattern="centered",
            patience_threshold_mean=24.0,
            patience_threshold_sd=8.0,
            notes="Balanced turnover. Tableside ordering. No reservations.",
        ),
        "cafe": BusinessModel(
            name="cafe",
            queue_type="single_queue",
            strategy_name="smallest_table_fit",
            tables=[TableInventory(seats=1, count=4), TableInventory(seats=2, count=6), TableInventory(seats=4, count=3)],
            generator_profile=GeneratorProfile(
                min_group_size=1,
                max_group_size=4,
                group_size_weights={1: 0.42, 2: 0.34, 3: 0.14, 4: 0.1},
                min_dining_duration=25,
                max_dining_duration=60,
                dining_duration_mean=38,
                dining_duration_sd=8,
            ),
            servers=2,
            ordering_type="hybrid",
            counter_order_time_min=1,
            counter_order_time_max=4,
            counter_order_time_mean=2,
            counter_order_time_sd=0.7,
            kiosks=1,
            kiosk_usage_percent=0.4,
            kiosk_order_time_min=1,
            kiosk_order_time_max=3,
            kiosk_order_time_mean=1.5,
            kiosk_order_time_sd=0.5,
            reservation_policy="none",
            arrival_pattern="left_skewed",
            patience_threshold_mean=12.0,
            patience_threshold_sd=4.0,
            notes="Solo and pair dominant. Mix of counter and self-service ordering. No reservations.",
        ),
        "food_truck": BusinessModel(
            name="food_truck",
            queue_type="single_queue",
            strategy_name="strict_fifo_fit",
            tables=[TableInventory(seats=1, count=3)],
            generator_profile=GeneratorProfile(
                min_group_size=1,
                max_group_size=1,
                group_size_weights={1: 1.0},
                min_dining_duration=1,
                max_dining_duration=5,
                dining_duration_mean=3,
                dining_duration_sd=1,
            ),
            servers=1,
            ordering_type="counter_only",
            counter_order_time_min=1,
            counter_order_time_max=4,
            counter_order_time_mean=2,
            counter_order_time_sd=0.8,
            kiosks=0,
            reservation_policy="none",
            arrival_pattern="uniform",
            patience_threshold_mean=7.0,
            patience_threshold_sd=3.0,
            notes="Single server. Order time models production time. Slot occupancy models pickup wait.",
        ),
    }
