from __future__ import annotations

import csv
import json
from pathlib import Path

from analysis.runner import AnalysisRunRecord, AnalysisSuiteResult

SUMMARY_METRICS = [
    "served_groups",
    "rejected_groups",
    "average_wait_time",
    "max_wait_time",
    "average_ordering_wait_time",
    "longest_queue_length",
    "table_utilization_rate",
    "server_utilization_rate",
    "service_level_rate",
    "abandoned_at_ordering",
    "abandoned_at_seating",
    "reservation_groups_served",
    "reservation_tables_released",
]


def write_analysis_reports(output_dir: Path, result: AnalysisSuiteResult) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    write_aggregate_json(output_dir / "aggregate_metrics.json", result)
    write_aggregate_csv(output_dir / "aggregate_metrics.csv", result)
    write_raw_csv(output_dir / "all_runs_raw_metrics.csv", result)
    write_markdown_report(output_dir / "analysis_report.md", result)


def write_aggregate_json(path: Path, result: AnalysisSuiteResult) -> None:
    payload = [
        {
            "experiment_name": aggregate.experiment_name,
            "run_name": aggregate.run_name,
            "description": aggregate.description,
            "metrics": aggregate.metrics,
            "expectation_results": aggregate.expectation_results,
        }
        for experiment in result.experiments
        for aggregate in experiment.aggregate_records
    ]
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_aggregate_csv(path: Path, result: AnalysisSuiteResult) -> None:
    rows = [
        {
            "experiment_name": aggregate.experiment_name,
            "run_name": aggregate.run_name,
            "description": aggregate.description,
            **aggregate.metrics,
            **{
                f"expectation_{metric}": passed
                for metric, passed in aggregate.expectation_results.items()
            },
        }
        for experiment in result.experiments
        for aggregate in experiment.aggregate_records
    ]
    _write_rows(path, rows)


def write_raw_csv(path: Path, result: AnalysisSuiteResult) -> None:
    rows = []
    for experiment in result.experiments:
        for record in experiment.run_records:
            rows.append(
                {
                    "experiment_name": record.experiment_name,
                    "run_name": record.run_name,
                    "seed": record.seed,
                    "scenario_path": record.scenario_path or "",
                    "result_path": record.result_path or "",
                    **record.metrics,
                }
            )
    _write_rows(path, rows)


def write_markdown_report(path: Path, result: AnalysisSuiteResult) -> None:
    lines = [
        f"# {result.title}",
        "",
        "This report was generated by running each configured scenario across its seeds "
        "and averaging the resulting simulation metrics.",
        "",
    ]
    for experiment in result.experiments:
        lines.extend(
            [
                f"## {experiment.scenario_name}",
                "",
                experiment.description or "No description provided.",
                "",
                _markdown_table(experiment.aggregate_records),
                "",
            ]
        )
        expectation_lines = _expectation_lines(experiment.aggregate_records)
        if expectation_lines:
            lines.extend(["Expectation checks:", *expectation_lines, ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def _markdown_table(aggregates) -> str:
    headers = [
        "Run",
        "Served",
        "Rejected",
        "Avg wait",
        "Max wait",
        "Order wait",
        "Max queue",
        "Table util.",
        "Ordering util.",
        "Service level",
    ]
    rows = [
        [
            aggregate.run_name,
            _fmt(aggregate.metrics.get("served_groups", 0.0)),
            _fmt(aggregate.metrics.get("rejected_groups", 0.0)),
            _fmt(aggregate.metrics.get("average_wait_time", 0.0)),
            _fmt(aggregate.metrics.get("max_wait_time", 0.0)),
            _fmt(aggregate.metrics.get("average_ordering_wait_time", 0.0)),
            _fmt(aggregate.metrics.get("longest_queue_length", 0.0)),
            _pct(aggregate.metrics.get("table_utilization_rate", 0.0)),
            _pct(aggregate.metrics.get("server_utilization_rate", 0.0)),
            _pct(aggregate.metrics.get("service_level_rate", 0.0)),
        ]
        for aggregate in aggregates
    ]
    align = ["---"] + ["---:"] * (len(headers) - 1)
    table = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(align) + " |",
    ]
    table.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(table)


def _expectation_lines(aggregates) -> list[str]:
    lines = []
    for aggregate in aggregates:
        for metric, passed in aggregate.expectation_results.items():
            status = "passed" if passed else "failed"
            lines.append(f"- `{aggregate.run_name}` expected `{metric}`: {status}.")
    return lines


def _write_rows(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = sorted({key for row in rows for key in row})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _fmt(value: float) -> str:
    return f"{value:.2f}"


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"
